
import type { Notification } from '@/lib/types';
import { subHours, subMinutes } from 'date-fns';

const LOGGED_IN_STAFF_ID = 'staff-003';

// This is a frontend simulation of a notification service.
// In a real backend, these would be generated by events.
let notifications: Notification[] = [
    {
        id: 'notif_1',
        type: 'new-order',
        title: 'New order #ORD-003 assigned',
        description: 'You have been assigned a new delivery for customer Noah Williams.',
        timestamp: subMinutes(new Date(), 5).toISOString(),
        read: false,
        link: '/dashboard/orders/ORD-003',
    },
    {
        id: 'notif_2',
        type: 'low-stock',
        title: 'Low Stock Warning',
        description: 'Product "Handmade Leather Shoes - Size 42" is low on stock (2 available).',
        timestamp: subHours(new Date(), 2).toISOString(),
        read: false,
        link: '/dashboard/products/SHOE-002',
    },
    {
        id: 'notif_3',
        type: 'new-order',
        title: 'Order #ORD-001 completed',
        description: 'You successfully delivered the order to Olivia Smith.',
        timestamp: subHours(new Date(), 8).toISOString(),
        read: true,
        link: '/dashboard/orders/ORD-001',
    },
];

export async function getNotifications(): Promise<Notification[]> {
    // In a real app, you'd fetch this for the logged-in user.
    // Here we just return the mock data.
    await new Promise(resolve => setTimeout(resolve, 300));
    return notifications.sort((a,b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
}

export async function markNotificationAsRead(id: string): Promise<boolean> {
    await new Promise(resolve => setTimeout(resolve, 100));
    const notification = notifications.find(n => n.id === id);
    if (notification) {
        notification.read = true;
        return true;
    }
    return false;
}

export async function markAllNotificationsAsRead(): Promise<boolean> {
     await new Promise(resolve => setTimeout(resolve, 100));
    notifications.forEach(n => n.read = true);
    return true;
}
